; PlatformIO Project Configuration File
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Upload settings
upload_protocol = teensy-gui

; Serial Monitor options
monitor_speed = 115200

; Library dependencies
lib_deps =
    adafruit/Adafruit INA260 Library@^1.5.0 ; voltage and current sensor library
    andrewrapp/XBee ; xbee library
    paulstoffregen/Time@^1.6.1 ; time library (used for the Teensy built-in RTC)
    duracopter/MAVLink v2 C library@^2.0
    https://github.com/mavlink/c_library_v2
